server:
  port: 8060
spring:
  application:
    name: guli-stock-nacos
  datasource:
    url: jdbc:mysql://localhost:3306/guli_stock?characterEncoding=utf-8&useSSL=false&serverTimezone=Asia/Shanghai&allowPublicKeyRetrieval=true
    username: root
    password: abcd1234
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    show-sql: true
  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848
        ip: localhost