server:
  port: 8010
spring:
  application:
    name: guli-order
  datasource:
    url: jdbc:mysql://localhost:3306/guli_order?characterEncoding=utf-8&useSSL=false&serverTimezone=Asia/Shanghai&allowPublicKeyRetrieval=true
    username: root
    password: abcd1234
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    show-sql: true
  sleuth:
    sampler:
      probability: 1.0
  zipkin:
    base-url: http://localhost:9411
    sender:
      type: web
eureka:
  instance:
    hostname: localhost
    prefer-ip-address: true
    ip-address: 127.0.0.1
    fetch-registry: true
  client:
    service-url:
      defaultZone: http://localhost:9000/eureka
logging:
  level:
    root: info
    com.atguigu.giliorder.feign: debug
#ribbon:
#  ConnectTimeout: 5000
#  ReadTimeout: 5000
management:
  endpoints:
    web:
      exposure:
        include: '*'
hystrix:
  dashboard:
    proxy-stream-allow-list: 'localhost'
