server:
  port: 8050
spring:
  application:
    name: guli-order-nacos
  datasource:
    url: jdbc:mysql://localhost:3306/guli_order?characterEncoding=utf-8&useSSL=false&serverTimezone=Asia/Shanghai&allowPublicKeyRetrieval=true
    username: root
    password: abcd1234
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    show-sql: true
  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848
        ip: localhost
      config:
        server-addr: localhost:8848
    sentinel:
      transport:
        port: 8719
        dashboard: localhost:8080
      eager: true
      filter:
        url-patterns: /**
logging:
  level:
    com.atguigu.guli.order.openfeign: debug
feign:
  sentinel:
    enabled: true